export const formConstants = {
  UPDATE_DASHBOARD_DATA: 'form/UPDATE_DASHBOARD_DATA',
  SET_ON_SYNC_FLAG: 'form/SET_ON_SYNC_FLAG',
  REGISTER_MODAL_OPEN: 'form/REGISTER_MODAL_OPEN',
  UPDATE_FILLING_FORM: 'form/UPDATE_FILLING_FORM',
};
